#!/bin/sh
#-----------------------------------------------------------------------
#
#	A script egy parameterfájl, amely a beállított paraméterekkel
#	meghívja coney logszimulátor egy vagy több - különböző módon -
#	felparaméterezett példányát
#
#	Author		: Istvan Diosi (www.szofiUSA.com)
#	Created		: 2016.07.21
#	Modify		: 2016.07.23
#
#-----------------------------------------------------------------------

#--------------------------------
#-- Equation --------------------
#--------------------------------
./coney_param -s=equation.lgdb -n=1000 -d=0

#--------------------------------
#-- payment ---------------------
#--------------------------------
./coney_param -s=payment.lgdb -n=1000 -d=0

#--------------------------------
#-- SWIFT -----------------------
#--------------------------------
./coney_param -s=swift.lgdb -n=1000 -d=0

#--------------------------------
#-- Apollo ----------------------
#--------------------------------
./coney_param -s=apollo.lgdb -n=1000 -d=0
